name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build --config ./docusaurus.docs.config.js

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOYER }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Upload to GCS
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './build'
          destination: 'fooday-docs'

  deploy-blog:
    name: Deploy Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build --config ./docusaurus.blog.config.js

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOYER }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Upload to GCS
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './build'
          destination: 'fooday-blog'