name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Docusaurus BuildDeploy Action
        uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: src
          git-user: pycxxx
          git-password: ${{ secrets.GITHUB_TOKEN }}